### PR TITLE
Use reload signal Upstart parameter for puma

### PR DESCRIPTION
**Pull request by bouk**
You can specify which signal to send
http://upstart.ubuntu.com/cookbook/#reload-signal

@charliesome @Sirupsen

### CODE REVIEW

**Comment by haileys** [comment]
I tried this and the version of upstart on the server didn't like it. You're welcome to give it a go and see if it works though.

**Comment by bouk** [comment]
Ah makes sense, it is only in the latest version https://bugs.launchpad.net/upstart/+bug/893021

Oh well, maybe another time then

**Comment by haileys** [comment]
If we used Arch this wouldn't be a problem :grinning:

**Comment by bouk** [comment]
I updated our server so it has the :sparkles: newest :sparkles: Ubuntu, now we can use it :)

**Comment by bouk** [comment]
OK :up:start works

**Comment by sirupsen** [comment]
@bouk do you mean we're on ubuntu 13.10?

**Comment by bouk** [comment]
Yes

**Comment by haileys** [comment]
:rocket:

**Comment by sirupsen** [comment]
Please upgrade vagrant as well

**Comment by bouk** [comment]
Well vagrant doesn't use upstart so it doesn't matter, I'll still do it for the sake of consistency though

**Comment by sirupsen** [comment]
Yep, exactly.

Also good job. :+1:

**Pull request merged**
